# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('user_screenname', models.CharField(max_length=255)),
                ('user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile_image_url', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('media_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_shown', models.BooleanField(default=False)),
                ('last_shown', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_app.Topic')),
            ],
        ),
    ]
