# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
